// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: scaleservice/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdatedRow []*ScaleRequest_Updatedrow `protobuf:"bytes,1,rep,name=updatedRow,proto3" json:"updatedRow,omitempty"`
}

func (x *ScaleRequest) Reset() {
	*x = ScaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scaleservice_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleRequest) ProtoMessage() {}

func (x *ScaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scaleservice_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleRequest.ProtoReflect.Descriptor instead.
func (*ScaleRequest) Descriptor() ([]byte, []int) {
	return file_scaleservice_service_proto_rawDescGZIP(), []int{0}
}

func (x *ScaleRequest) GetUpdatedRow() []*ScaleRequest_Updatedrow {
	if x != nil {
		return x.UpdatedRow
	}
	return nil
}

type ScaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    string               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error   *ScaleResponse_ERROR `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ScaleResponse) Reset() {
	*x = ScaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scaleservice_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleResponse) ProtoMessage() {}

func (x *ScaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scaleservice_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleResponse.ProtoReflect.Descriptor instead.
func (*ScaleResponse) Descriptor() ([]byte, []int) {
	return file_scaleservice_service_proto_rawDescGZIP(), []int{1}
}

func (x *ScaleResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ScaleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScaleResponse) GetError() *ScaleResponse_ERROR {
	if x != nil {
		return x.Error
	}
	return nil
}

type ScaleRequest_Updatedrow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColName  string `protobuf:"bytes,1,opt,name=colName,proto3" json:"colName,omitempty"`
	Value    string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	DataType string `protobuf:"bytes,3,opt,name=dataType,proto3" json:"dataType,omitempty"`
}

func (x *ScaleRequest_Updatedrow) Reset() {
	*x = ScaleRequest_Updatedrow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scaleservice_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScaleRequest_Updatedrow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleRequest_Updatedrow) ProtoMessage() {}

func (x *ScaleRequest_Updatedrow) ProtoReflect() protoreflect.Message {
	mi := &file_scaleservice_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleRequest_Updatedrow.ProtoReflect.Descriptor instead.
func (*ScaleRequest_Updatedrow) Descriptor() ([]byte, []int) {
	return file_scaleservice_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ScaleRequest_Updatedrow) GetColName() string {
	if x != nil {
		return x.ColName
	}
	return ""
}

func (x *ScaleRequest_Updatedrow) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ScaleRequest_Updatedrow) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

type ScaleResponse_ERROR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ScaleResponse_ERROR) Reset() {
	*x = ScaleResponse_ERROR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scaleservice_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScaleResponse_ERROR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleResponse_ERROR) ProtoMessage() {}

func (x *ScaleResponse_ERROR) ProtoReflect() protoreflect.Message {
	mi := &file_scaleservice_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleResponse_ERROR.ProtoReflect.Descriptor instead.
func (*ScaleResponse_ERROR) Descriptor() ([]byte, []int) {
	return file_scaleservice_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ScaleResponse_ERROR) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ScaleResponse_ERROR) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_scaleservice_service_proto protoreflect.FileDescriptor

var file_scaleservice_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x72,
	0x6f, 0x77, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x1a, 0x58,
	0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x72, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x61,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x61,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x35, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4a,
	0x0a, 0x0c, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a,
	0x0a, 0x13, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x61,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scaleservice_service_proto_rawDescOnce sync.Once
	file_scaleservice_service_proto_rawDescData = file_scaleservice_service_proto_rawDesc
)

func file_scaleservice_service_proto_rawDescGZIP() []byte {
	file_scaleservice_service_proto_rawDescOnce.Do(func() {
		file_scaleservice_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_scaleservice_service_proto_rawDescData)
	})
	return file_scaleservice_service_proto_rawDescData
}

var file_scaleservice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scaleservice_service_proto_goTypes = []interface{}{
	(*ScaleRequest)(nil),            // 0: pb.ScaleRequest
	(*ScaleResponse)(nil),           // 1: pb.ScaleResponse
	(*ScaleRequest_Updatedrow)(nil), // 2: pb.ScaleRequest.Updatedrow
	(*ScaleResponse_ERROR)(nil),     // 3: pb.ScaleResponse.ERROR
}
var file_scaleservice_service_proto_depIdxs = []int32{
	2, // 0: pb.ScaleRequest.updatedRow:type_name -> pb.ScaleRequest.Updatedrow
	3, // 1: pb.ScaleResponse.error:type_name -> pb.ScaleResponse.ERROR
	0, // 2: pb.ScaleService.ScaleServiceRequest:input_type -> pb.ScaleRequest
	1, // 3: pb.ScaleService.ScaleServiceRequest:output_type -> pb.ScaleResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scaleservice_service_proto_init() }
func file_scaleservice_service_proto_init() {
	if File_scaleservice_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scaleservice_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scaleservice_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scaleservice_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScaleRequest_Updatedrow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scaleservice_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScaleResponse_ERROR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scaleservice_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scaleservice_service_proto_goTypes,
		DependencyIndexes: file_scaleservice_service_proto_depIdxs,
		MessageInfos:      file_scaleservice_service_proto_msgTypes,
	}.Build()
	File_scaleservice_service_proto = out.File
	file_scaleservice_service_proto_rawDesc = nil
	file_scaleservice_service_proto_goTypes = nil
	file_scaleservice_service_proto_depIdxs = nil
}
