// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SampleRequest struct {
	Event                string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	MailParams           []string `protobuf:"bytes,2,rep,name=mail_params,json=mailParams,proto3" json:"mail_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleRequest) Reset()         { *m = SampleRequest{} }
func (m *SampleRequest) String() string { return proto.CompactTextString(m) }
func (*SampleRequest) ProtoMessage()    {}
func (*SampleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *SampleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleRequest.Unmarshal(m, b)
}
func (m *SampleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleRequest.Marshal(b, m, deterministic)
}
func (m *SampleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleRequest.Merge(m, src)
}
func (m *SampleRequest) XXX_Size() int {
	return xxx_messageInfo_SampleRequest.Size(m)
}
func (m *SampleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SampleRequest proto.InternalMessageInfo

func (m *SampleRequest) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *SampleRequest) GetMailParams() []string {
	if m != nil {
		return m.MailParams
	}
	return nil
}

type SampleResponse struct {
	Data                 string                `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                *SampleResponse_ERROR `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SampleResponse) Reset()         { *m = SampleResponse{} }
func (m *SampleResponse) String() string { return proto.CompactTextString(m) }
func (*SampleResponse) ProtoMessage()    {}
func (*SampleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *SampleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleResponse.Unmarshal(m, b)
}
func (m *SampleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleResponse.Marshal(b, m, deterministic)
}
func (m *SampleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleResponse.Merge(m, src)
}
func (m *SampleResponse) XXX_Size() int {
	return xxx_messageInfo_SampleResponse.Size(m)
}
func (m *SampleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SampleResponse proto.InternalMessageInfo

func (m *SampleResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SampleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SampleResponse) GetError() *SampleResponse_ERROR {
	if m != nil {
		return m.Error
	}
	return nil
}

type SampleResponse_ERROR struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleResponse_ERROR) Reset()         { *m = SampleResponse_ERROR{} }
func (m *SampleResponse_ERROR) String() string { return proto.CompactTextString(m) }
func (*SampleResponse_ERROR) ProtoMessage()    {}
func (*SampleResponse_ERROR) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1, 0}
}

func (m *SampleResponse_ERROR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleResponse_ERROR.Unmarshal(m, b)
}
func (m *SampleResponse_ERROR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleResponse_ERROR.Marshal(b, m, deterministic)
}
func (m *SampleResponse_ERROR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleResponse_ERROR.Merge(m, src)
}
func (m *SampleResponse_ERROR) XXX_Size() int {
	return xxx_messageInfo_SampleResponse_ERROR.Size(m)
}
func (m *SampleResponse_ERROR) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleResponse_ERROR.DiscardUnknown(m)
}

var xxx_messageInfo_SampleResponse_ERROR proto.InternalMessageInfo

func (m *SampleResponse_ERROR) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SampleResponse_ERROR) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SampleRequest)(nil), "pb.SampleRequest")
	proto.RegisterType((*SampleResponse)(nil), "pb.SampleResponse")
	proto.RegisterType((*SampleResponse_ERROR)(nil), "pb.SampleResponse.ERROR")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0xad, 0xab, 0x74, 0x4a, 0x05, 0x47, 0x0f, 0xa1, 0x17, 0x97, 0x9e, 0xf6, 0x94,
	0x43, 0xc5, 0x9b, 0x57, 0x7b, 0x13, 0xcb, 0xf4, 0x07, 0x48, 0x76, 0x3b, 0xc8, 0x42, 0x37, 0x89,
	0x49, 0xda, 0x7f, 0xe4, 0xff, 0x94, 0x9d, 0xb8, 0xa0, 0x88, 0xb7, 0xf7, 0x1e, 0xe1, 0xbd, 0xcc,
	0x07, 0xcb, 0xc8, 0xe1, 0xdc, 0x77, 0xac, 0x7d, 0x70, 0xc9, 0x61, 0xe9, 0xdb, 0xf5, 0x16, 0x96,
	0x7b, 0x33, 0xf8, 0x23, 0x13, 0x7f, 0x9c, 0x38, 0x26, 0xbc, 0x83, 0x8a, 0xcf, 0x6c, 0x93, 0x2a,
	0xea, 0xa2, 0x99, 0x53, 0x36, 0x78, 0x0f, 0x8b, 0xc1, 0xf4, 0xc7, 0x37, 0x6f, 0x82, 0x19, 0xa2,
	0x2a, 0xeb, 0x59, 0x33, 0x27, 0x18, 0xa3, 0x9d, 0x24, 0xeb, 0xcf, 0x02, 0xae, 0xa7, 0xa2, 0xe8,
	0x9d, 0x8d, 0x8c, 0x08, 0x17, 0x07, 0x93, 0xcc, 0x77, 0x91, 0x68, 0x54, 0x70, 0x35, 0x70, 0x8c,
	0xe6, 0x9d, 0x55, 0x29, 0xf1, 0x64, 0x51, 0x43, 0xc5, 0x21, 0xb8, 0xa0, 0x66, 0x75, 0xd1, 0x2c,
	0x36, 0x4a, 0xfb, 0x56, 0xff, 0x2e, 0xd4, 0xcf, 0x44, 0xaf, 0x44, 0xf9, 0xd9, 0xea, 0x11, 0x2a,
	0xf1, 0xe3, 0x4c, 0xe7, 0x0e, 0x2c, 0x33, 0x15, 0x89, 0xfe, 0x7f, 0x66, 0xf3, 0x32, 0xdd, 0xbb,
	0xcf, 0x28, 0xf0, 0x09, 0x6e, 0x73, 0xb0, 0x1b, 0x99, 0x6c, 0x4f, 0xb6, 0x4b, 0xbd, 0xb3, 0x78,
	0xf3, 0x73, 0x5f, 0xc8, 0xac, 0xf0, 0xef, 0x97, 0xda, 0x4b, 0x21, 0xf9, 0xf0, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x21, 0x70, 0x1a, 0xee, 0x5a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SampleServiceClient is the client API for SampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SampleServiceClient interface {
	SampleProtoFunction(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (*SampleResponse, error)
}

type sampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleServiceClient(cc grpc.ClientConnInterface) SampleServiceClient {
	return &sampleServiceClient{cc}
}

func (c *sampleServiceClient) SampleProtoFunction(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (*SampleResponse, error) {
	out := new(SampleResponse)
	err := c.cc.Invoke(ctx, "/pb.SampleService/SampleProtoFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleServiceServer is the server API for SampleService service.
type SampleServiceServer interface {
	SampleProtoFunction(context.Context, *SampleRequest) (*SampleResponse, error)
}

// UnimplementedSampleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSampleServiceServer struct {
}

func (*UnimplementedSampleServiceServer) SampleProtoFunction(ctx context.Context, req *SampleRequest) (*SampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SampleProtoFunction not implemented")
}

func RegisterSampleServiceServer(s *grpc.Server, srv SampleServiceServer) {
	s.RegisterService(&_SampleService_serviceDesc, srv)
}

func _SampleService_SampleProtoFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).SampleProtoFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SampleService/SampleProtoFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).SampleProtoFunction(ctx, req.(*SampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SampleService",
	HandlerType: (*SampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SampleProtoFunction",
			Handler:    _SampleService_SampleProtoFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
